Add initial functionality for I2C and SPI.
adafruit/Adafruit_CircuitPython_BMP3XX pull request #1
Opened 2018-11-01 22:32 UTC by caternuson

* basic readings: pressure, temperature, altitude
* over sampling individually settable for pressure and temperature
* IIR filter coefficient

2018-11-04 19:29 UTC, tannewt requested changes
One thing but good otherwise.

2018-11-04 19:29 UTC, tannewt commented on adafruit_bmp3xx.py
> +        self.sea_level_pressure = 1013.25 # hPa @ MSL
Add a """comment""" after this so sea_level_pressure is shown in RTD.

2018-11-04 21:32 UTC, ladyada commented
i tested this code, seems to work fine so after the minor update, we can merge!

2018-11-05 16:23 UTC, ladyada approved these changes
tested with hardware

2018-11-05 22:28 UTC, tannewt approved these changes
Ok, looks good! Thanks!

2018-11-05 22:29 UTC, merged